In [ ]:
import pandas as pd

df = pd.read_csv('pokemon_data.csv') #read csv file
dfxl = pd.read_excel('pokemon_data.xlsx') #read xl file
df.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [ ]:
#Top rows

print(df.head(3))

   #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80

   Generation  Legendary
0           1      False
1           1      False
2           1      False

In [ ]:
#Bottom rows 

print(df.tail(3))

       #                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170
799  721            Volcanion     Fire  Water  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
797      130     70           6       True
798      130     80           6       True
799       90     70           6       True

In [ ]:
dfxl.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [ ]:
dftxt = pd.read_csv('pokemon_data.txt')
dftxt.head(7)

  #\tName\tType 1\tType 2\tHP\tAttack\tDefense\tSp. Atk\tSp. Def\tSpeed\tGeneration\tLegendary
0  1\tBulbasaur\tGrass\tPoison\t45\t49\t49\t65\t6...
1  2\tIvysaur\tGrass\tPoison\t60\t62\t63\t80\t80\...
2  3\tVenusaur\tGrass\tPoison\t80\t82\t83\t100\t1...
3  3\tVenusaurMega Venusaur\tGrass\tPoison\t80\t1...
4  4\tCharmander\tFire\t\t39\t52\t43\t60\t50\t65\...
5  5\tCharmeleon\tFire\t\t58\t64\t58\t80\t65\t80\...
6  6\tCharizard\tFire\tFlying\t78\t84\t78\t109\t8...

In [ ]:
#Using delimiter
dftxt1 = pd.read_csv('pokemon_data.txt', delimiter='\t')
dftxt1.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [ ]:
#Reading headers

print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [ ]:
#Read specific column

df['Name'][0:5]

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [ ]:
df.Name[0:5]

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [ ]:
print(df[['Name', 'Type 1']])

                      Name   Type 1
0                Bulbasaur    Grass
1                  Ivysaur    Grass
2                 Venusaur    Grass
3    VenusaurMega Venusaur    Grass
4               Charmander     Fire
..                     ...      ...
795                Diancie     Rock
796    DiancieMega Diancie     Rock
797    HoopaHoopa Confined  Psychic
798     HoopaHoopa Unbound  Psychic
799              Volcanion     Fire

[800 rows x 2 columns]

In [ ]:
print(df[['Name', 'Type 1', 'HP']][0:5])

                    Name Type 1  HP
0              Bulbasaur  Grass  45
1                Ivysaur  Grass  60
2               Venusaur  Grass  80
3  VenusaurMega Venusaur  Grass  80
4             Charmander   Fire  39

In [ ]:
#to print rows

df.iloc[1:4]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [ ]:
df.iloc[2,1]

'Venusaur'

In [ ]:
df.iloc[2:3]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [ ]:
df.iloc[2]

#                    3
Name          Venusaur
Type 1           Grass
Type 2          Poison
HP                  80
Attack              82
Defense             83
Sp. Atk            100
Sp. Def            100
Speed               80
Generation           1
Legendary        False
Name: 2, dtype: object

In [ ]:
#Iterations

for index, row in df.iterrows():
    print(index, row)

Streaming output truncated to the last 5000 lines.
Attack            50
Defense          100
Sp. Atk          100
Sp. Def          200
Speed             50
Generation         3
Legendary       True
Name: 415, dtype: object
416 #                   379
Name          Registeel
Type 1            Steel
Type 2              NaN
HP                   80
Attack               75
Defense             150
Sp. Atk              75
Sp. Def             150
Speed                50
Generation            3
Legendary          True
Name: 416, dtype: object
417 #                 380
Name           Latias
Type 1         Dragon
Type 2        Psychic
HP                 80
Attack             80
Defense            90
Sp. Atk           110
Sp. Def           130
Speed             110
Generation          3
Legendary        True
Name: 417, dtype: object
418 #                           380
Name          LatiasMega Latias
Type 1                   Dragon
Type 2                  Psychic
HP                           80
Attack                      100
Defense                     120
Sp. Atk                     140
Sp. Def                     150
Speed                       110
Generation                    3
Legendary                  True
Name: 418, dtype: object
419 #                 381
Name           Latios
Type 1         Dragon
Type 2        Psychic
HP                 80
Attack             90
Defense            80
Sp. Atk           130
Sp. Def           110
Speed             110
Generation          3
Legendary        True
Name: 419, dtype: object
420 #                           381
Name          LatiosMega Latios
Type 1                   Dragon
Type 2                  Psychic
HP                           80
Attack                      130
Defense                     100
Sp. Atk                     160
Sp. Def                     120
Speed                       110
Generation                    3
Legendary                  True
Name: 420, dtype: object
421 #                382
Name          Kyogre
Type 1         Water
Type 2           NaN
HP               100
Attack           100
Defense           90
Sp. Atk          150
Sp. Def          140
Speed             90
Generation         3
Legendary       True
Name: 421, dtype: object
422 #                             382
Name          KyogrePrimal Kyogre
Type 1                      Water
Type 2                        NaN
HP                            100
Attack                        150
Defense                        90
Sp. Atk                       180
Sp. Def                       160
Speed                          90
Generation                      3
Legendary                    True
Name: 422, dtype: object
423 #                 383
Name          Groudon
Type 1         Ground
Type 2            NaN
HP                100
Attack            150
Defense           140
Sp. Atk           100
Sp. Def            90
Speed              90
Generation          3
Legendary        True
Name: 423, dtype: object
424 #                               383
Name          GroudonPrimal Groudon
Type 1                       Ground
Type 2                         Fire
HP                              100
Attack                          180
Defense                         160
Sp. Atk                         150
Sp. Def                          90
Speed                            90
Generation                        3
Legendary                      True
Name: 424, dtype: object
425 #                  384
Name          Rayquaza
Type 1          Dragon
Type 2          Flying
HP                 105
Attack             150
Defense             90
Sp. Atk            150
Sp. Def             90
Speed               95
Generation           3
Legendary         True
Name: 425, dtype: object
426 #                               384
Name          RayquazaMega Rayquaza
Type 1                       Dragon
Type 2                       Flying
HP                              105
Attack                          180
Defense                         100
Sp. Atk                         180
Sp. Def                         100
Speed                           115
Generation                        3
Legendary                      True
Name: 426, dtype: object
427 #                 385
Name          Jirachi
Type 1          Steel
Type 2        Psychic
HP                100
Attack            100
Defense           100
Sp. Atk           100
Sp. Def           100
Speed             100
Generation          3
Legendary        True
Name: 427, dtype: object
428 #                            386
Name          DeoxysNormal Forme
Type 1                   Psychic
Type 2                       NaN
HP                            50
Attack                       150
Defense                       50
Sp. Atk                      150
Sp. Def                       50
Speed                        150
Generation                     3
Legendary                   True
Name: 428, dtype: object
429 #                            386
Name          DeoxysAttack Forme
Type 1                   Psychic
Type 2                       NaN
HP                            50
Attack                       180
Defense                       20
Sp. Atk                      180
Sp. Def                       20
Speed                        150
Generation                     3
Legendary                   True
Name: 429, dtype: object
430 #                             386
Name          DeoxysDefense Forme
Type 1                    Psychic
Type 2                        NaN
HP                             50
Attack                         70
Defense                       160
Sp. Atk                        70
Sp. Def                       160
Speed                          90
Generation                      3
Legendary                    True
Name: 430, dtype: object
431 #                           386
Name          DeoxysSpeed Forme
Type 1                  Psychic
Type 2                      NaN
HP                           50
Attack                       95
Defense                      90
Sp. Atk                      95
Sp. Def                      90
Speed                       180
Generation                    3
Legendary                  True
Name: 431, dtype: object
432 #                 387
Name          Turtwig
Type 1          Grass
Type 2            NaN
HP                 55
Attack             68
Defense            64
Sp. Atk            45
Sp. Def            55
Speed              31
Generation          4
Legendary       False
Name: 432, dtype: object
433 #                388
Name          Grotle
Type 1         Grass
Type 2           NaN
HP                75
Attack            89
Defense           85
Sp. Atk           55
Sp. Def           65
Speed             36
Generation         4
Legendary      False
Name: 433, dtype: object
434 #                  389
Name          Torterra
Type 1           Grass
Type 2          Ground
HP                  95
Attack             109
Defense            105
Sp. Atk             75
Sp. Def             85
Speed               56
Generation           4
Legendary        False
Name: 434, dtype: object
435 #                  390
Name          Chimchar
Type 1            Fire
Type 2             NaN
HP                  44
Attack              58
Defense             44
Sp. Atk             58
Sp. Def             44
Speed               61
Generation           4
Legendary        False
Name: 435, dtype: object
436 #                  391
Name          Monferno
Type 1            Fire
Type 2        Fighting
HP                  64
Attack              78
Defense             52
Sp. Atk             78
Sp. Def             52
Speed               81
Generation           4
Legendary        False
Name: 436, dtype: object
437 #                   392
Name          Infernape
Type 1             Fire
Type 2         Fighting
HP                   76
Attack              104
Defense              71
Sp. Atk             104
Sp. Def              71
Speed               108
Generation            4
Legendary         False
Name: 437, dtype: object
438 #                393
Name          Piplup
Type 1         Water
Type 2           NaN
HP                53
Attack            51
Defense           53
Sp. Atk           61
Sp. Def           56
Speed             40
Generation         4
Legendary      False
Name: 438, dtype: object
439 #                  394
Name          Prinplup
Type 1           Water
Type 2             NaN
HP                  64
Attack              66
Defense             68
Sp. Atk             81
Sp. Def             76
Speed               50
Generation           4
Legendary        False
Name: 439, dtype: object
440 #                  395
Name          Empoleon
Type 1           Water
Type 2           Steel
HP                  84
Attack              86
Defense             88
Sp. Atk            111
Sp. Def            101
Speed               60
Generation           4
Legendary        False
Name: 440, dtype: object
441 #                396
Name          Starly
Type 1        Normal
Type 2        Flying
HP                40
Attack            55
Defense           30
Sp. Atk           30
Sp. Def           30
Speed             60
Generation         4
Legendary      False
Name: 441, dtype: object
442 #                  397
Name          Staravia
Type 1          Normal
Type 2          Flying
HP                  55
Attack              75
Defense             50
Sp. Atk             40
Sp. Def             40
Speed               80
Generation           4
Legendary        False
Name: 442, dtype: object
443 #                   398
Name          Staraptor
Type 1           Normal
Type 2           Flying
HP                   85
Attack              120
Defense              70
Sp. Atk              50
Sp. Def              60
Speed               100
Generation            4
Legendary         False
Name: 443, dtype: object
444 #                399
Name          Bidoof
Type 1        Normal
Type 2           NaN
HP                59
Attack            45
Defense           40
Sp. Atk           35
Sp. Def           40
Speed             31
Generation         4
Legendary      False
Name: 444, dtype: object
445 #                 400
Name          Bibarel
Type 1         Normal
Type 2          Water
HP                 79
Attack             85
Defense            60
Sp. Atk            55
Sp. Def            60
Speed              71
Generation          4
Legendary       False
Name: 445, dtype: object
446 #                   401
Name          Kricketot
Type 1              Bug
Type 2              NaN
HP                   37
Attack               25
Defense              41
Sp. Atk              25
Sp. Def              41
Speed                25
Generation            4
Legendary         False
Name: 446, dtype: object
447 #                    402
Name          Kricketune
Type 1               Bug
Type 2               NaN
HP                    77
Attack                85
Defense               51
Sp. Atk               55
Sp. Def               51
Speed                 65
Generation             4
Legendary          False
Name: 447, dtype: object
448 #                  403
Name             Shinx
Type 1        Electric
Type 2             NaN
HP                  45
Attack              65
Defense             34
Sp. Atk             40
Sp. Def             34
Speed               45
Generation           4
Legendary        False
Name: 448, dtype: object
449 #                  404
Name             Luxio
Type 1        Electric
Type 2             NaN
HP                  60
Attack              85
Defense             49
Sp. Atk             60
Sp. Def             49
Speed               60
Generation           4
Legendary        False
Name: 449, dtype: object
450 #                  405
Name            Luxray
Type 1        Electric
Type 2             NaN
HP                  80
Attack             120
Defense             79
Sp. Atk             95
Sp. Def             79
Speed               70
Generation           4
Legendary        False
Name: 450, dtype: object
451 #                406
Name           Budew
Type 1         Grass
Type 2        Poison
HP                40
Attack            30
Defense           35
Sp. Atk           50
Sp. Def           70
Speed             55
Generation         4
Legendary      False
Name: 451, dtype: object
452 #                  407
Name          Roserade
Type 1           Grass
Type 2          Poison
HP                  60
Attack              70
Defense             65
Sp. Atk            125
Sp. Def            105
Speed               90
Generation           4
Legendary        False
Name: 452, dtype: object
453 #                  408
Name          Cranidos
Type 1            Rock
Type 2             NaN
HP                  67
Attack             125
Defense             40
Sp. Atk             30
Sp. Def             30
Speed               58
Generation           4
Legendary        False
Name: 453, dtype: object
454 #                   409
Name          Rampardos
Type 1             Rock
Type 2              NaN
HP                   97
Attack              165
Defense              60
Sp. Atk              65
Sp. Def              50
Speed                58
Generation            4
Legendary         False
Name: 454, dtype: object
455 #                  410
Name          Shieldon
Type 1            Rock
Type 2           Steel
HP                  30
Attack              42
Defense            118
Sp. Atk             42
Sp. Def             88
Speed               30
Generation           4
Legendary        False
Name: 455, dtype: object
456 #                   411
Name          Bastiodon
Type 1             Rock
Type 2            Steel
HP                   60
Attack               52
Defense             168
Sp. Atk              47
Sp. Def             138
Speed                30
Generation            4
Legendary         False
Name: 456, dtype: object
457 #               412
Name          Burmy
Type 1          Bug
Type 2          NaN
HP               40
Attack           29
Defense          45
Sp. Atk          29
Sp. Def          45
Speed            36
Generation        4
Legendary     False
Name: 457, dtype: object
458 #                             413
Name          WormadamPlant Cloak
Type 1                        Bug
Type 2                      Grass
HP                             60
Attack                         59
Defense                        85
Sp. Atk                        79
Sp. Def                       105
Speed                          36
Generation                      4
Legendary                   False
Name: 458, dtype: object
459 #                             413
Name          WormadamSandy Cloak
Type 1                        Bug
Type 2                     Ground
HP                             60
Attack                         79
Defense                       105
Sp. Atk                        59
Sp. Def                        85
Speed                          36
Generation                      4
Legendary                   False
Name: 459, dtype: object
460 #                             413
Name          WormadamTrash Cloak
Type 1                        Bug
Type 2                      Steel
HP                             60
Attack                         69
Defense                        95
Sp. Atk                        69
Sp. Def                        95
Speed                          36
Generation                      4
Legendary                   False
Name: 460, dtype: object
461 #                414
Name          Mothim
Type 1           Bug
Type 2        Flying
HP                70
Attack            94
Defense           50
Sp. Atk           94
Sp. Def           50
Speed             66
Generation         4
Legendary      False
Name: 461, dtype: object
462 #                415
Name          Combee
Type 1           Bug
Type 2        Flying
HP                30
Attack            30
Defense           42
Sp. Atk           30
Sp. Def           42
Speed             70
Generation         4
Legendary      False
Name: 462, dtype: object
463 #                   416
Name          Vespiquen
Type 1              Bug
Type 2           Flying
HP                   70
Attack               80
Defense             102
Sp. Atk              80
Sp. Def             102
Speed                40
Generation            4
Legendary         False
Name: 463, dtype: object
464 #                   417
Name          Pachirisu
Type 1         Electric
Type 2              NaN
HP                   60
Attack               45
Defense              70
Sp. Atk              45
Sp. Def              90
Speed                95
Generation            4
Legendary         False
Name: 464, dtype: object
465 #                418
Name          Buizel
Type 1         Water
Type 2           NaN
HP                55
Attack            65
Defense           35
Sp. Atk           60
Sp. Def           30
Speed             85
Generation         4
Legendary      False
Name: 465, dtype: object
466 #                  419
Name          Floatzel
Type 1           Water
Type 2             NaN
HP                  85
Attack             105
Defense             55
Sp. Atk             85
Sp. Def             50
Speed              115
Generation           4
Legendary        False
Name: 466, dtype: object
467 #                 420
Name          Cherubi
Type 1          Grass
Type 2            NaN
HP                 45
Attack             35
Defense            45
Sp. Atk            62
Sp. Def            53
Speed              35
Generation          4
Legendary       False
Name: 467, dtype: object
468 #                 421
Name          Cherrim
Type 1          Grass
Type 2            NaN
HP                 70
Attack             60
Defense            70
Sp. Atk            87
Sp. Def            78
Speed              85
Generation          4
Legendary       False
Name: 468, dtype: object
469 #                 422
Name          Shellos
Type 1          Water
Type 2            NaN
HP                 76
Attack             48
Defense            48
Sp. Atk            57
Sp. Def            62
Speed              34
Generation          4
Legendary       False
Name: 469, dtype: object
470 #                   423
Name          Gastrodon
Type 1            Water
Type 2           Ground
HP                  111
Attack               83
Defense              68
Sp. Atk              92
Sp. Def              82
Speed                39
Generation            4
Legendary         False
Name: 470, dtype: object
471 #                 424
Name          Ambipom
Type 1         Normal
Type 2            NaN
HP                 75
Attack            100
Defense            66
Sp. Atk            60
Sp. Def            66
Speed             115
Generation          4
Legendary       False
Name: 471, dtype: object
472 #                  425
Name          Drifloon
Type 1           Ghost
Type 2          Flying
HP                  90
Attack              50
Defense             34
Sp. Atk             60
Sp. Def             44
Speed               70
Generation           4
Legendary        False
Name: 472, dtype: object
473 #                  426
Name          Drifblim
Type 1           Ghost
Type 2          Flying
HP                 150
Attack              80
Defense             44
Sp. Atk             90
Sp. Def             54
Speed               80
Generation           4
Legendary        False
Name: 473, dtype: object
474 #                 427
Name          Buneary
Type 1         Normal
Type 2            NaN
HP                 55
Attack             66
Defense            44
Sp. Atk            44
Sp. Def            56
Speed              85
Generation          4
Legendary       False
Name: 474, dtype: object
475 #                 428
Name          Lopunny
Type 1         Normal
Type 2            NaN
HP                 65
Attack             76
Defense            84
Sp. Atk            54
Sp. Def            96
Speed             105
Generation          4
Legendary       False
Name: 475, dtype: object
476 #                             428
Name          LopunnyMega Lopunny
Type 1                     Normal
Type 2                   Fighting
HP                             65

In [ ]:
for index, row in df.iterrows():
    print(index, row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 Flabébé
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

In [ ]:
df.iterrows()

In [ ]:
df.loc[df['Type 1'] == "Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
 df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [ ]:
df.sort_values('Name')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [ ]:
df.sort_values('Name', ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [ ]:
df.sort_values(['Type 1','HP'], ascending=[1, 0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [ ]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [ ]:
#Total column of stats

df['Total'] = df['HP'] + df['Attack'] ++ df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

df.head()

,#,Name,Type 1,Type 2,Total,Legendary,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,318,False,False,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,405,False,False,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,525,False,False,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,625,False,False,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,309,False,False,39,52,43,60,50,65,1

In [ ]:
df = df.drop(columns=['Total'])
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [ ]:
df['Total'] = df.iloc[:, 4:10].sum(axis=1)
df.head()

,#,Name,Type 1,Type 2,Total,Legendary,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,747.0,False,False,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,960.0,False,False,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,1260.0,False,False,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,1534.0,False,False,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,711.0,False,False,39,52,43,60,50,65,1

In [ ]:
#Reorder columns  
cols = list(df.columns)

df = df[cols[0:4] + [cols[-1]] + cols[4:12]]
df.head()

,#,Name,Type 1,Type 2,Generation,Total,Legendary,Legendary,Legendary,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def
0,1,Bulbasaur,Grass,Poison,1,318,False,False,False,False,45,49,49,65,65
1,2,Ivysaur,Grass,Poison,1,405,False,False,False,False,60,62,63,80,80
2,3,Venusaur,Grass,Poison,1,525,False,False,False,False,80,82,83,100,100
3,3,VenusaurMega Venusaur,Grass,Poison,1,625,False,False,False,False,80,100,123,122,120
4,4,Charmander,Fire,NaN,1,309,False,False,False,False,39,52,43,60,50

In [ ]:
df.to_csv('modified.csv')

In [ ]:
df.to_excel('modified1.xlsx')

In [ ]:
df.to_csv('modified2.txt', sep='/')

In [ ]:
df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

In [ ]:
df.loc[(df['Type 1'] == 'Grass') | (df['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False